id: P000536
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG5774
  title: ཧོར་གྱི་ཆོས་འབྱུང་
  author: ''
  volumes:
    2bdc4a4e1c374ecd8350ad61cedb3dca:
      image_group_id: I1KG5782
      title: Volume 1 of hor gyi chos 'byung
      volume_number: 1
      total_pages: 248
      base_file: v001.txt
